### Here is the implemetation of "Fast Semi-Supervised Node Embedding Learning via Structural and Label-Aware Optimization"

In [ ]:
import pandas as pd 
import numpy as np 
import os
import networkx as nx
import random
import torch
from torch_geometric.utils import to_dense_adj

### reading the dataset :

In [181]:

data_dir = os.path.expanduser("cora")

edgelist = pd.read_csv(os.path.join(data_dir, "cora.cites"), sep='\t', header=None, names=["target", "source"])
edgelist["label"] = "cites"

In [182]:
edgelist.head(5)

   target   source  label
0      35     1033  cites
1      35   103482  cites
2      35   103515  cites
3      35  1050679  cites
4      35  1103960  cites

In [183]:
Gnx = nx.from_pandas_edgelist(edgelist, edge_attr="label")
nx.set_node_attributes(Gnx, "paper", "label")

In [184]:
Gnx.nodes[1103985]

{'label': 'paper'}

In [185]:
feature_names = ["w_{}".format(ii) for ii in range(1433)]
column_names =  feature_names + ["subject"]
node_data = pd.read_csv(os.path.join(data_dir, "cora.content"), sep='\t', header=None, names=column_names)

In [186]:
node_data.head(5)

,w_0,w_1,w_2,w_3,w_4,w_5,w_6,w_7,w_8,w_9,...,w_1424,w_1425,w_1426,w_1427,w_1428,w_1429,w_1430,w_1431,w_1432,subject
31336,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,Neural_Networks
1061127,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Rule_Learning
1106406,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Reinforcement_Learning
13195,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Reinforcement_Learning
37879,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Probabilistic_Methods

In [187]:
node_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2708 entries, 31336 to 24043
Columns: 1434 entries, w_0 to subject
dtypes: int64(1433), object(1)
memory usage: 29.6+ MB

In [188]:
node_data.shape

(2708, 1434)

In [189]:
set(node_data["subject"])

{'Case_Based',
 'Genetic_Algorithms',
 'Neural_Networks',
 'Probabilistic_Methods',
 'Reinforcement_Learning',
 'Rule_Learning',
 'Theory'}

In [190]:
node_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2708 entries, 31336 to 24043
Columns: 1434 entries, w_0 to subject
dtypes: int64(1433), object(1)
memory usage: 29.6+ MB

## Getting Started:

In [191]:
from torch_geometric.datasets import Planetoid
dataset = Planetoid(root='Cora', name='Cora')

data = dataset[0]
print(f'Dataset: {dataset}:')
print('======================')
print(f'Number of graphs: {len(dataset)}')
print(f'Number of features: {dataset.num_features}')
print(f'Number of classes: {dataset.num_classes}')

print(f'Number of nodes: {data.num_nodes}')
print(f'Number of edges: {data.num_edges}')
print(f'Average node degree: {data.num_edges / data.num_nodes:.2f}')
print(f'Number of training nodes: {data.train_mask.sum()}')
print(f'Training node label rate: {int(data.train_mask.sum()) / data.num_nodes:.2f}')
print(f'Contains isolated nodes: {data.contains_isolated_nodes()}')
print(f'Contains self-loops: {data.contains_self_loops()}')
print(f'Is undirected: {data.is_undirected()}')

Dataset: Cora():
======================
Number of graphs: 1
Number of features: 1433
Number of classes: 7
Number of nodes: 2708
Number of edges: 10556
Average node degree: 3.90
Number of training nodes: 140
Training node label rate: 0.05
Contains isolated nodes: False
Contains self-loops: False
Is undirected: True

C:\Users\mehul\AppData\Local\Temp\ipykernel_19796\1433470767.py:16: UserWarning: 'contains_isolated_nodes' is deprecated, use 'has_isolated_nodes' instead
  print(f'Contains isolated nodes: {data.contains_isolated_nodes()}')
C:\Users\mehul\AppData\Local\Temp\ipykernel_19796\1433470767.py:17: UserWarning: 'contains_self_loops' is deprecated, use 'has_self_loops' instead
  print(f'Contains self-loops: {data.contains_self_loops()}')

### Init.

In [192]:
device = "cpu"

In [193]:
original_embed = data.x

# Adjacency matrix
A = to_dense_adj(data.edge_index)[0]

# Labels for each node:
labels = data.y

# Verification of dimensions
print(f'Original embedding shape: {original_embed.shape}')     # [2708, 1433]
print(f'Adjacency Matrix shape: {A.shape}') # [2708, 2708]
print(f'Labels shape: {labels.shape}')               # [2708]

Original embedding shape: torch.Size([2708, 1433])
Adjacency Matrix shape: torch.Size([2708, 2708])
Labels shape: torch.Size([2708])

In [194]:
# initial random feature ,atrix :

S = torch.rand(2708, 145, device=device)  

print(f'Random embedding shape: {S.shape}')

Random embedding shape: torch.Size([2708, 145])

In [195]:
# Qr decomposition of the random feature matrix:

Q, R = torch.linalg.qr(S)
S_ortho = Q
print(f'Orthogonalized embedding shape: {S_ortho.shape}')

Orthogonalized embedding shape: torch.Size([2708, 145])

In [196]:
S = S_ortho

In [197]:
A = A.to(device)
S = S.to(device)
labels = labels.to(device)

### Masking the labels:

- masking rate : 0.5 (MCAR)

In [198]:
labels

tensor([3, 4, 4,  ..., 3, 3, 3])

In [199]:
# masking 50 poercent of the lables at random:
num_nodes = labels.shape[0]
num_mask = int(0.5 * num_nodes)
mask_indices = torch.randperm(num_nodes)[:num_mask]
labels_masked = labels.clone()
labels_masked[mask_indices] = -1

In [200]:
A

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 1., 0.]])

### Biased Random Walk :
(Hyperparams for Cora Dataset)

- r = 20
- L = 4 (l)
- L'= 1 (L)

In [201]:
labels_masked = labels_masked.to(device)

so here I need to map the nodes from labels_masked, A and S, to calcualte the

In [202]:
labels_list = labels_masked

In [203]:
num_nodes = labels_list.shape[0]
adj_list = [[] for i in range(num_nodes)]
edges = A.nonzero(as_tuple=False)
edges_list = edges.tolist()
for src, dst in edges_list:
        adj_list[src].append(dst)

In [204]:
def random_walk(labels_list, adj_list, r, l, L, device = device):
 
    
    W_f = {}  # labelled nodes list for all the unlabeled nodes
    
    for node_id, label_value in enumerate(labels_list):
        
        if label_value == -1:
            W = []
            
            for walk in range(r):
                current_node = node_id
                labeled_count = 0
                for step in range(l):
                    neighbors = adj_list[current_node]
                    if not neighbors:
                        break
                    next_node = random.choice(neighbors) # randomly pick the neighbor 
                    if labels_list[next_node] != -1:
                        if labeled_count < L:
                            W.append(next_node)
                            labeled_count += 1
                        else:
                            break
                            # moving to the next node:
                    current_node = next_node
            
            W_f[node_id] = W
            
    return W_f

In [205]:
W_f = random_walk(labels_list, adj_list, r=20, l=4, L=1)

here is the list of labelled neighbors obtained for the first masked node:

In [206]:
len(W_f) # lists for the masked nodes

1354

In [207]:
import torch

def modularity(A, edgelist, S, device = device):

    m = len(edgelist)
    d = A.sum(dim=1, keepdim=True) 
    TS = S.sum(dim=0, keepdim=True)
    AS = A @ S  
    degree_correction = d * TS
    factor = 1.0 / (2 * m)
    Q_prop = factor * (AS - factor * degree_correction)
    
    return Q_prop

In [208]:

def sup_reg(S, labels_list, device = device):

    
    grad_sup = torch.zeros_like(S, device=device)
    
    label_set = set(labels_list)
    
    for current_class in label_set:
        if current_class == -1:
            continue

        node_indices = [i for i, label in enumerate(labels_list) if label == current_class]
        class_embeddings = S[node_indices]
        mu_c = class_embeddings.mean(dim=0)
        grad_sup[node_indices] = class_embeddings - mu_c
        
    return grad_sup

In [209]:
W_f.items()

dict_items([(5, [1765, 1358]), (8, [269, 1996, 1996, 269, 281, 1996, 281, 281, 269, 269, 281, 281, 1996, 1996, 269, 269, 1996, 1996, 281, 1996]), (9, []), (11, [1839, 1839, 2384, 1839, 1842, 1839, 1839, 1839, 1839, 1839, 1839, 1839, 1013, 1839, 1839]), (15, [1271, 1093, 2367, 1271, 1093, 1093, 1271, 1271, 2367, 1271, 1271, 1271, 2367, 2367, 2367, 2367, 2367, 1271, 1271]), (16, [2444, 364, 364, 2444, 2444, 364, 364, 364, 364, 2444, 364, 2444, 364, 2444, 364, 2444, 364, 1358]), (18, [1448, 1623, 589, 2145, 1772, 1623, 1623, 505, 308, 1772, 2145, 699, 109, 2145, 910, 2145, 2145]), (20, [1825, 2374, 2374, 1072, 1404, 2374, 1825, 2269, 2269, 2269, 1404, 400, 2269, 1072, 1072, 1072, 2374, 1404]), (24, [2117, 17, 2142, 297, 1986, 1986, 17, 343, 467, 143, 2706]), (25, [1301, 1301, 1301, 2317, 2317, 2317, 2011, 1301, 1301, 1301, 2011, 2011, 2317, 1301, 2011, 1301, 1301, 2011, 1301, 2011]), (26, [123, 99, 123, 99, 2455, 2455, 2455, 123, 123, 2455, 99, 2455, 99, 2455, 123, 99, 99]), (27, [1809, 549, 1814, 2361, 1581, 2, 2041, 531, 2361, 1811, 1823, 1808, 2027, 2027]), (28, [1721, 1721, 1003, 1721, 1003, 1721, 1003, 1721, 1721, 246, 1003, 246, 246, 1721, 1721, 1721, 1003, 1003, 1003, 1721]), (29, [89, 963, 2237, 963, 89, 963, 2237, 963, 963, 963, 963, 963, 963, 963, 963]), (30, [1468, 738, 738, 305, 2344, 738, 65, 2162, 2162, 1922, 6, 1358, 1468, 2344, 1358, 2162]), (31, [1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594, 1594]), (32, [1973, 1850, 1850, 1973, 1973, 666, 1973, 1850, 1850, 1973, 1373, 502, 1850, 502, 1373, 1973, 1973, 1850, 1850, 1850]), (35, [895, 895, 895, 895, 895, 1704, 895, 440, 895, 895, 895, 1910, 1704, 440, 895, 895, 895, 895, 895]), (37, [1387, 2428, 1387, 1387, 1387, 2480, 2428, 1387, 2428, 465, 1387, 830]), (38, [2044, 863, 863, 863, 1160, 1590, 2044, 1160, 1160, 1807, 863, 2122, 1160, 863, 863, 1160, 1160, 863]), (43, [1530, 1530, 963, 963, 963, 963, 1530, 1530, 1530, 627, 884, 963, 1530, 2399, 89, 2399, 963]), (44, [1582, 2701, 1582, 2701, 1582, 2701, 2701, 2701, 1582, 1582, 2701, 1582, 2701, 2701, 2701, 1582, 2701, 2701, 2701, 2701]), (47, [1182, 1182, 1182, 1182, 1182, 2029, 2029, 2029, 1182, 1825, 2029]), (48, [2205, 2471, 2, 2471, 2205, 2205, 2471, 1986, 1031, 1823, 2041, 2041, 2205]), (49, [2, 1891, 2, 2, 1807, 224, 722, 1812, 2035, 1497, 2037, 1891, 224, 1807, 1614]), (50, [590, 1707, 648, 1955, 2275, 1917, 1958, 540, 590, 1619, 648, 720, 590, 720, 1707, 1619]), (54, [767, 767, 767, 767, 767, 767, 767, 767, 767, 1062, 767, 767, 104, 767, 309, 104, 104, 2320, 767, 767]), (55, [2035, 651, 2020, 2020, 65, 2020, 2020, 2021, 1156, 1907, 2020, 325, 1156, 651, 815, 860, 2020, 815, 1907]), (56, [1616, 1616, 447, 447, 1616, 1616, 1013, 1616, 1616, 1616, 447, 1616, 1616, 1616, 447, 447, 1616, 1616, 447]), (59, [105, 609, 1358, 1627, 1358, 1358, 609, 1358, 1742, 1358, 2651, 609, 1358, 1725, 1358, 105, 105, 609]), (60, [1079, 815, 2480, 1614, 2021, 355, 1387, 419, 2021, 2480]), (62, [485, 485, 485, 485, 485, 485, 485, 485, 485, 485, 485, 485, 485, 485, 485, 485, 485, 485, 485, 485]), (63, [984, 2035, 984, 984, 2035, 984]), (66, []), (67, [540, 282, 540, 540, 540, 540, 540, 282, 540, 540, 540, 540, 540, 540, 540, 540, 540, 540, 282]), (69, [2653, 1914, 1351, 1351, 2653, 1351, 2051, 1013, 1013, 1351, 1351, 1013, 2051, 2109, 2653, 2189, 1914, 1013, 1914, 2310]), (72, [1103, 1103, 1103, 1358, 1103, 1103, 1358, 1103, 1103, 1103, 1358, 1358, 1103, 1358, 1103, 1103, 1358, 1358, 1358, 1358]), (73, [797, 558, 1358, 1358, 797, 1136, 558, 1035, 834, 1136, 1723, 558, 1035, 797, 449, 1136, 558, 1136, 2596, 2596]), (74, [2052, 274, 2419, 2294, 2419, 2153, 2333, 437, 399, 2153, 2419, 2052, 2199, 1125]), (76, [2178, 1741, 1713, 2178, 973, 2178, 2178, 815, 2178, 2178, 1658, 1309, 1658, 1658, 356, 2178, 2178]), (78, [1219, 1219, 1219, 1219, 1219, 2304, 1219, 1219, 1219]), (80, [736, 2180, 1117, 1628, 1117, 1117, 1628, 1628, 2181, 1117, 1117, 1117, 1117, 1117, 1117]), (81, [2180, 525, 2180, 315, 527, 525, 527, 527, 2180, 315, 527, 525, 527, 527, 527, 525, 527]), (87, [42, 42, 42, 2217, 816, 2217, 42, 42, 2217, 2217, 42, 842, 42, 842, 42, 842, 42, 842]), (88, [2178, 1013, 1677, 815, 1847, 2016, 1741, 1847, 437, 745, 1309, 356, 1079, 356, 2000, 1309, 2015, 2010]), (90, [155, 817, 817, 155, 155, 155, 155, 1358, 1358, 155, 155, 817, 155, 1358, 1689, 1358, 155, 155, 1358, 155]), (92, [898, 1836, 898, 898, 1836, 1836, 1836, 1836, 1836, 898, 1836, 1836, 898, 898, 898, 898, 1836, 898, 898, 898]), (93, [645, 2151, 550, 437, 2151, 2151, 645, 550, 645, 437, 645, 645, 550, 2151, 2151, 645, 550, 2151, 645, 437]), (95, [2364, 2199, 1628, 552, 6, 2199, 1628, 2202, 1535, 2199, 2199, 2183, 2183, 2199, 861, 2199, 525, 2197]), (96, [2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217, 2217]), (98, [1013, 1013, 1013, 1013, 1013, 1013, 1013, 1013, 1013, 1013, 1013, 1013]), (100, [2056, 2056, 2181, 2056, 2056, 2056, 2056, 2056, 2056, 2056, 1125, 2056, 2056, 6, 2056, 2199, 315]), (101, [281, 1358, 1358, 1358, 281, 1358, 2596, 281, 1358, 281, 281, 1358, 281, 1358, 1358, 2596, 1358, 1358, 281, 1358]), (106, [2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461, 2461]), (108, [2158, 1835, 2160, 2160, 2158, 2158, 2158, 2160]), (110, [2460, 2460, 1513, 631, 2279, 2460, 1161, 2460, 2279, 1513, 2279, 1161, 1161, 536, 1161]), (116, [2395, 447, 2227, 1675, 1076, 1076, 1076, 1076, 1076, 1076, 2395, 2395, 2395, 1076, 1076, 1914, 1675, 1076, 2017]), (117, [2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537]), (118, [255, 554, 1029, 1690, 2280, 903, 1645, 1507, 255, 554, 1538, 1507, 1538, 554, 842, 903, 2112, 388, 1690, 1538]), (119, [1901, 1455, 1901, 441, 1901, 1360, 1549, 1549, 1901, 1901, 1901, 1549, 1901, 1455, 1901, 1901]), (122, [99, 2455, 99, 2455, 99, 2455, 2455, 2455, 2455, 99, 99, 2455, 99, 99, 99, 99, 99, 2455]), (125, [2363, 2363, 458, 2363, 458, 458, 458, 458, 458, 2363, 2363, 2363, 2363, 2363, 2363, 2363, 458, 2363, 458, 2363]), (127, [99, 123, 99, 123, 99, 99, 99, 99, 123, 99, 123, 99, 99, 123, 123, 123, 123, 123, 99]), (128, [2269, 370, 1415, 370, 1825, 370, 1825, 720, 1619, 370, 2269, 370, 370, 370, 370, 2269, 370, 370, 370]), (129, [701, 701, 701, 441, 441, 701, 701, 701, 441, 701, 701, 441, 441, 701, 701, 441, 701, 701, 701, 701]), (130, [2178, 436, 2017, 436, 1713, 436, 2017, 2017, 2017, 436, 436, 436, 2017, 436, 436, 2136, 841, 2017, 436, 1847]), (131, [834, 834, 834, 2169, 2169, 834, 834, 834, 834, 2169, 834, 2169, 2169, 834, 834, 2169, 834, 2169, 834, 834]), (132, [645, 1961, 1713, 1961, 645, 1549, 1227, 1961, 1883, 1168]), (133, [1258, 2096, 1623, 1777, 1258, 109, 1258, 109, 109, 1623, 1777, 1623, 563, 308, 1777, 1777, 109, 399, 2096]), (136, [831, 831, 831, 831, 831, 831, 831, 831, 831, 831, 831, 831, 831, 831, 831, 831, 831, 831, 831, 831]), (138, [1045, 236, 1772, 1251, 236, 487, 112, 236, 973, 1787, 1499, 236, 1499, 2091, 236, 2085, 2324, 236, 308]), (139, [103, 638, 2026, 103, 1772, 910, 103, 910, 1623, 308, 910, 1609, 2145, 910, 103, 1623, 563, 103]), (142, [525, 525, 1628, 1628, 525, 2181, 1117, 525, 2181, 2181, 525, 2181, 2364, 525, 2180, 2181, 1628]), (144, [145, 145, 145, 1593, 1593, 1593, 145, 1593, 1593, 1593, 495, 1593, 145, 145, 1593, 1593, 1593, 145, 1593]), (146, [1468, 1907, 1468, 1468, 1468, 2059, 2059, 1494, 1907, 1468, 1156, 1907, 2059, 1907, 1907, 1468, 2059, 1907]), (147, [1976, 1976, 1519, 1976, 1976, 1976, 1976, 1976, 1519, 1519, 1519, 1976, 1519, 1976, 1976, 1519, 1519, 1519, 1519, 1976]), (148, [2518, 2041, 698, 2518, 2518, 2471, 2518, 2518]), (149, [2025, 738, 2136, 2344, 2280, 2162, 2025, 2025, 2118, 1468, 2136, 2344, 2025, 738, 2025, 305, 61, 738]), (150, [1942, 310, 1942, 1942, 310, 1942, 1942, 310, 1942, 310, 1942, 1942, 310, 1942, 310, 1942, 914, 914, 914, 1942]), (151, [1703, 1986, 2336, 1986, 1519, 1703, 1986, 1969, 1971, 1986, 2259, 2237, 1986, 2237, 1986, 1986, 1986]), (152, [884, 2399, 1157, 2237, 627, 884, 963, 2399, 627, 963, 1530, 963, 2399, 963, 884, 2399]), (153, [656, 1623, 2046, 1623, 2096, 109, 1623, 1623, 109, 1623, 1623, 1623, 1623, 236, 109, 236, 236, 1623]), (156, [1358, 1689, 155, 155, 817, 1689, 1689, 155, 1358, 155, 155, 1689, 1689, 817, 1689, 817, 817, 817, 1689, 817]), (159, [2308, 171, 2308, 2076, 2308, 2308, 791, 2308, 2308, 2037, 2308, 2004, 2308, 2308, 2308, 2308, 2308, 2308, 2308]), (160, [745, 277, 1583, 1309, 2000, 2009, 745, 2027, 745, 277, 748, 1986, 571, 2009, 277, 1986, 277, 745, 2009]), (162, [1667, 1667, 2103, 2103, 415, 815, 1667, 1677, 1667, 1713, 2017, 1667, 1667, 815, 2022]), (163, [1182, 2029, 1825]), (164, [1614, 1905, 1079, 1905, 1079, 1907, 1907, 1905, 239, 65, 1905, 2136, 1079]), (166, [2617, 271, 271, 271, 271, 2617, 271, 271, 271, 2617, 271, 271, 271, 2617, 2617, 2617, 2617, 2617, 2617, 271]), (168, [2438, 167, 167, 167, 167, 167, 167, 167, 167, 2438, 167, 2438, 2438, 2438, 167, 2438, 2438, 2438, 167, 167]), (169, [2706, 2706, 2706, 1986, 1986, 2706, 2706, 2706, 2706, 1986, 2706, 1986, 1986, 2706, 2706, 2706, 1986]), (172, [2187, 2187, 2187, 2187, 756, 2187, 2187, 756, 756, 2349, 2187, 1423, 756, 756, 2187, 756]), (173, [1033, 1358, 1358, 1358, 2279, 1358, 1033, 1358, 1725, 2372, 1033, 1033, 1358, 2168, 1721, 2372]), (174, [609, 1358, 609, 609, 1742, 1742, 933, 1742, 1742, 2334, 1358, 2334, 1742, 2334, 1742, 1358, 1358, 2334, 1358]), (180, [791, 2667, 2076, 2037, 2037, 158, 158, 1807, 158, 171, 2037, 1823, 2004, 2667, 1807, 791, 158, 2004, 218, 2037]), (181, [1973, 262, 1013, 850, 850, 1013, 1163, 262, 850, 1973, 1013, 2480, 1013, 2480, 1013, 1914, 1013]), (182, [183, 997, 183, 183, 997, 183, 183, 183, 183, 183, 183, 997, 997, 997, 997, 183, 183, 183, 997, 997]), (184, []), (187, []), (188, [1317, 1358, 1714, 1358, 1714, 1714, 2492, 1714, 1731, 2492, 2220, 1358, 1358, 2220, 1040, 1358, 1358, 1145]), (189, [2476, 1072, 1072, 1072, 1072, 1072, 1072, 1072, 1072, 1072, 1072, 1072, 1072, 2460, 1072]), (190, [2135, 2135, 2135, 2135, 2135, 2135, 2135, 2135, 2135, 2135, 2135, 2135, 2135, 2135, 2135]), (192, [2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472, 2472]), (193, [458, 458, 458, 441, 441, 458, 458, 441, 441, 441, 441, 458, 441, 441, 441, 441, 458, 441, 441, 441]), (194, [1342, 1379, 1342, 2646, 1320, 1380, 2646, 1342, 1380, 1380, 1379, 1703, 2648, 2646, 2646, 1379, 2646]), (195, [1839, 1839, 94, 1839, 1839, 94, 94, 94, 1839, 1839, 94, 94, 1839, 1839, 1839, 1839, 1839, 1839, 94, 1839]), (196, [2122, 2122, 1889, 588, 2001, 698, 2122, 863, 2122, 863, 2001, 2406, 2122, 863, 2122, 2122, 2122, 1669, 2122]), (197, [231, 231, 231, 179, 179, 231, 1997, 179, 231, 179, 179, 179, 179, 179, 179, 179, 179, 179]), (199, [1097, 857, 465, 1865, 1095, 767, 467, 1097, 235, 963, 1115, 465]), (201, [387, 158, 1852, 1075, 157, 1874, 1986, 845, 297, 1003, 1986, 547, 1348, 1301, 2138]), (203, [963, 1115, 963, 854, 1115, 1115, 854, 857, 854, 230, 857, 1115, 1115, 854, 963, 857, 857]), (204, [415, 415, 415, 415, 415, 415, 415, 415, 415, 415, 415, 415, 415, 415, 415, 415, 415, 415, 415, 415]), (205, [1075, 235, 1853, 216, 2568, 1479, 1853, 261, 1097, 235, 1097, 467, 1440, 1846, 465, 1787, 1986]), (206, [71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71]), (210, [1906, 1079, 1614, 1614, 1906, 1906, 1614, 1905, 1626, 1906, 1079, 1907, 1906, 1906]), (211, [1171, 239, 1171, 1930, 2305, 356, 1986, 2305, 1905, 356, 239, 2015, 356, 1677]), (212, [1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290, 1290]), (213, [1593, 1593, 145, 145, 1593, 145, 145, 1593, 495, 1593, 1593, 145, 145, 145, 1593, 145, 1593, 145]), (225, []), (226, [13, 216, 1986, 231, 2080, 935, 547, 231, 143, 633, 1874, 231, 261, 1863]), (227, [609, 609, 933, 609, 933, 933, 1358, 933, 1742, 609, 609, 609, 609, 933]), (228, [1373, 1373, 1373, 322, 322, 1871, 1721, 322, 1721, 1721, 322, 1871, 1721, 1721, 1373, 322, 1721, 322, 1721, 1871]), (229, [1405, 33, 1405, 2280, 2118, 2118, 1405, 1930, 1405, 1405, 2118, 2118, 1405, 1405, 1508, 1405, 2118, 2118, 2118, 1405]), (232, [1986, 1986, 729, 165, 1986, 1440, 1986, 1986, 1846, 1986, 1871, 1986, 231, 231, 231, 1986, 1986]), (233, [371, 370, 370, 2269, 1825, 2269, 1415, 720, 370, 370, 370, 1825, 1404, 1072, 370, 2269]), (234, [2591, 610, 610, 610, 2591, 2591, 2591, 2591, 2591, 610, 610, 2591, 610, 610, 610, 2591, 2591, 610, 610, 2591]), (237, [2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539, 2539]), (240, [1423, 2346, 756, 2348, 756, 756, 576, 2187, 756, 756, 756, 756]), (243, [2474, 2474, 2474, 2648, 2474, 2648, 2474, 1686, 2648, 2648, 1686, 2648, 2648, 2474, 217]), (247, [2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583, 2583]), (249, [1884, 1978, 1884, 1978, 356, 1978, 1884, 1884, 2024, 1884, 1884, 1884, 1978, 1978, 1978, 1884, 1884]), (250, [2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429, 2429]), (252, [2485, 2485, 973, 1973, 973, 2485, 973, 973, 711, 2485, 1973, 2485, 1973, 973, 1973, 973, 2485, 973, 973, 711]), (253, [251, 1300, 1363, 251, 251, 219, 251, 251, 251, 1935, 40, 251, 251, 295, 219, 251, 2508]), (254, [219, 1211, 1363, 1211, 40, 40, 812, 1211, 1211, 1211, 40, 1211, 1211, 40, 1211, 1340, 1211, 251, 1940, 1211]), (257, [2180, 2181, 1117, 2180, 2056, 736, 2181, 2055, 2181, 965, 1117, 1628, 1117, 2197, 1006, 736]), (258, [2237, 2237, 761, 89, 1094, 963, 761, 1703, 1094, 89, 1094, 761, 89, 761, 89, 761, 963]), (259, [2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537, 2537]), (260, [365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365]), (263, [364, 364, 364, 364, 364, 1103, 364, 364, 364, 364, 1103, 364, 364, 364, 364, 1103, 364]), (264, [1826, 1826, 1826, 1826, 1902, 1902, 1902, 1902, 1902, 1902, 1826, 1902, 1826, 1902, 1826, 1826, 1902, 1826]), (265, [540, 1619, 2275, 540, 540, 590, 648, 1707, 241, 2272, 2272, 1619, 720, 1707]), (266, [1105, 601, 601, 601, 1523, 2227, 1879, 601, 2227, 2227, 2227, 2227, 2227, 2227, 2227, 2227]), (268, [1072, 2392, 1072, 2392, 2083, 2391, 2392, 1358, 1358, 1072, 2452, 1072, 2391, 2391, 2203, 1035]), (270, [1195, 842, 2280, 1195, 1195, 838, 1195, 1850, 502, 2280, 1195, 1195, 838, 1973, 2280, 2280, 838, 838, 838]), (272, [1288, 1677, 2017, 2016, 1713, 1713]), (279, [1172, 502, 1195, 2280, 1708, 2280, 2280, 2344, 838, 2344, 666, 1850, 242, 1973, 1973, 2344]), (280, [1535, 1535, 1370, 1535, 2153, 2419, 1203, 1535, 1203, 1110, 2294, 1203, 485, 1535, 1535, 1203, 1535, 1535]), (287, [2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705, 2705]), (288, [938, 938, 938, 938, 938, 938, 938, 938, 938, 938, 938, 938, 938, 938, 938, 938]), (290, [328, 328, 1136, 328, 1765, 480, 2372, 1171, 1725, 536, 1765, 1725, 328, 1610, 1171, 797, 1171]), (291, [2346, 2186, 2186, 2348, 756, 2186, 756, 2346, 2186, 2349, 1423, 1423]), (292, [1036, 1036, 1036, 1036, 1036, 1036, 1036, 1036, 1036, 1036, 1036, 1036, 1036, 1036, 1036, 1036, 1036]), (294, [126, 426, 302, 573, 887, 126, 1072, 1779, 387, 973, 236, 836]), (296, [364, 1718, 2452, 364, 1718, 2452, 2452, 2452, 1718, 364, 364, 364, 364, 2452, 1718]), (299, [302, 2498, 2498, 2386, 2386, 2498, 2386, 911, 911, 638, 1510, 2498, 2386, 1046, 2498, 2386, 638]), (300, [415, 2227, 415, 415, 2011, 415, 841, 415, 415, 571, 2395, 415, 415, 2227, 2015]), (301, [2476, 2492, 1145, 1719, 552, 2492, 748, 2492, 2492, 2476, 2492, 748, 2492, 2492, 2492, 1358, 2492, 2492]), (303, [1623, 1623, 2143, 2143, 1777, 302, 2143, 302, 2143, 2143, 1623, 2143, 2143, 1623, 2143]), (304, [2151, 2344, 2151, 1708, 1172, 2151, 784, 1708, 242, 1172, 666, 2151, 1172, 1172, 1172, 1172, 666]), (306, [1623, 542, 563, 112, 2079, 1572, 426, 2080, 887, 2080, 79, 1009, 1572, 655, 1193, 487, 699, 124]), (312, [289, 2523, 1035, 289, 1610, 1358, 1610, 289, 1610, 1610, 1610, 2391, 289, 1725, 1610, 289, 1035, 1610, 1072, 1072]), (314, [2000, 2000, 2000, 2000, 1623, 2000, 1623, 2000, 2000, 1623, 2000, 2000, 2000, 2000, 2000, 2000, 1623, 1623, 2000, 1623]), (317, [1505, 1505, 109, 1788, 963, 1787, 963, 1777, 963, 1505, 109, 1505, 109, 109, 887, 1779, 1505]), (318, [563, 563, 109, 109, 109, 1986, 109, 563, 563, 563, 143, 109, 109, 109, 308, 1986]), (320, [2250, 2250, 2248, 2250, 2250, 2248, 2248, 432, 432, 432, 2248, 2248, 432, 432, 2248, 2248]), (323, [2020, 356, 2022, 651, 2020, 1848, 2022, 2020, 2020, 2020, 2022, 2022, 2022, 415, 2022, 2020, 2020]), (326, [1754, 154, 1358, 1754, 1358, 1754, 154, 154, 1754, 1754, 154, 1358, 1358, 154, 1358, 154, 154, 1754, 1754, 1358]), (329, [958, 2598, 2322, 2598, 2598, 2598, 887, 2598, 2598, 36, 2598, 2598, 2598, 1770, 1072]), (330, [91, 91, 91, 91, 91, 91, 1505, 2001, 2001, 1505, 1505, 2122, 91, 1505, 91, 1505, 91, 1505, 1505, 1505]), (331, [415, 815, 2480, 2480, 2480, 2480, 860, 415, 2480, 389, 860, 1370, 2480, 860, 415, 415, 2480]), (334, [1013, 1661, 1013, 2485, 1013, 763, 2183, 763, 1013, 1013, 2108, 736, 979, 861, 2108]), (335, [1874, 1075, 1863, 1986, 1323, 1986, 1986, 1855, 1986, 1986, 1986, 1986, 231, 1986, 158, 1986]), (337, [1499, 1358, 1214, 1735, 1214, 1358, 1499, 1358, 1358, 1358, 2324, 2324, 1358, 2046, 1358, 1499, 1572, 1358, 1499]), (338, [219, 1363, 1931, 251, 1577, 1934, 1934, 1477, 251, 1300, 251, 1934, 1340, 1300, 297, 1934, 1177, 1933, 1934, 1934]), (340, [584, 584, 2463, 584, 2463, 584, 2463, 2463, 584, 2463, 2463, 584, 2463, 2463, 2463, 584, 2463, 2463, 2463, 2463]), (341, [613, 613, 1358, 2169, 1358, 109, 1358, 613, 613, 1609, 613, 2597, 1358, 1358, 1358]), (344, [854, 854, 1885, 1879, 854, 2323, 97, 854, 2323, 441, 441, 854, 441, 441, 2323, 441, 935, 854, 389, 389]), (345, [207, 207, 2595, 207, 2595, 178, 178, 2595, 1130, 1130, 178, 207, 1130, 178, 178, 2036]), (347, [525, 315, 2180, 527, 1841, 525, 315, 525, 525, 527, 525, 527, 525, 525, 525, 525, 315, 525, 1841, 525]), (348, [2250, 2250, 2250, 2250, 2250, 2250, 2248, 2250, 2250, 2248, 2248, 2248, 2248, 432, 2250, 2250, 2250, 2250]), (349, [419, 419, 419, 465, 465, 465, 419, 465, 465, 419, 2428, 465, 465, 419, 419, 419, 419, 2428, 419, 2428]), (350, [1623, 656, 2084, 2085, 112, 505, 1623, 2085, 2327, 308, 308, 2085, 656, 2084, 1772, 1623, 2085, 1623, 1623]), (351, [13, 1812, 2379, 94, 1808, 1813, 1820, 568, 1815, 224, 568, 13, 171, 716, 549, 1062]), (353, [1250, 202, 202, 202, 202, 202, 202, 202, 202, 202, 1345, 202, 1345, 1250, 1250, 202, 202, 202, 1345, 2507]), (354, [1839, 77, 77, 1839, 1072, 77, 1839, 1839, 77, 1839, 1839, 1072, 1072, 77, 1072, 77]), (358, [364, 364, 364, 364, 364, 2444, 364, 364, 364, 2444, 364, 364]), (359, [389, 1620, 1620, 389, 1072, 1620, 389, 1620, 1620, 1412, 1620, 2208, 754, 389, 389, 1620, 1620, 389, 1620]), (360, [1182, 1409, 448, 1409, 1409, 1409, 1182, 1409, 1409, 2553, 1409, 1409, 1409, 1409, 1409, 1825, 1409]), (362, [1320, 1703, 2623, 443, 1703, 22, 2623, 1906, 94, 2623, 443, 1703, 1703, 2623, 443, 2623, 1703]), (363, [1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003, 1003]), (367, [2083, 1757, 2083, 2391, 2391, 2392, 2083, 2083, 2083, 2083, 1757, 2083, 2083, 1757, 2083, 2083]), (368, [2518, 2248, 2248, 1194, 2518, 2393, 996, 2393, 996, 2248, 2248, 2393, 2393, 996, 2518, 996, 2248, 996]), (373, [2333, 2055, 6, 1481, 6, 6, 6, 2333, 6, 1481, 6, 485, 6]), (374, [273, 509, 413, 509, 2147, 413, 413, 273, 509, 413, 273, 273, 273, 413, 413, 509, 509, 413]), (375, [1087, 963, 2401, 2401, 2401, 2401, 2401, 2401, 1087, 963, 963, 963, 2401, 2399, 963, 2401, 2401, 963, 2401]), (376, [1583, 672, 1583, 672, 220, 672, 672, 1583, 220, 22

In [210]:
import torch

def attention_wts(W_f, S, device = device):

    attention_wts = {}
    for node, labelled_neigh in W_f.items():
        if not labelled_neigh:
            attention_wts[node] = torch.tensor([], device=device)  
            continue

        neighbors_idx = torch.tensor(labelled_neigh, device=device)
        s_i = S[node]
        
        s_neighbors = S[neighbors_idx]
        
        sim = torch.matmul(s_neighbors, s_i)
        
        # Apply softmax across the sim to get the final weights
        # This executes the exp(s_ij) / sum(exp(s_ik)) formula exactly (Equation 7)
        w_ij = torch.softmax(sim, dim=0)
        
        attention_wts[node] = w_ij
        
    return attention_wts

In [211]:
# saving the index of the masked nodes to be considered for semi supervised loss :

masked = []

for idx, nodes in enumerate(labels_list):
    if nodes == -1:
        masked.append(idx)

In [212]:
masked

[5,
 8,
 9,
 11,
 15,
 16,
 18,
 20,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 35,
 37,
 38,
 43,
 44,
 47,
 48,
 49,
 50,
 54,
 55,
 56,
 59,
 60,
 62,
 63,
 66,
 67,
 69,
 72,
 73,
 74,
 76,
 78,
 80,
 81,
 87,
 88,
 90,
 92,
 93,
 95,
 96,
 98,
 100,
 101,
 106,
 108,
 110,
 116,
 117,
 118,
 119,
 122,
 125,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 136,
 138,
 139,
 142,
 144,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 156,
 159,
 160,
 162,
 163,
 164,
 166,
 168,
 169,
 172,
 173,
 174,
 180,
 181,
 182,
 184,
 187,
 188,
 189,
 190,
 192,
 193,
 194,
 195,
 196,
 197,
 199,
 201,
 203,
 204,
 205,
 206,
 210,
 211,
 212,
 213,
 225,
 226,
 227,
 228,
 229,
 232,
 233,
 234,
 237,
 240,
 243,
 247,
 249,
 250,
 252,
 253,
 254,
 257,
 258,
 259,
 260,
 263,
 264,
 265,
 266,
 268,
 270,
 272,
 279,
 280,
 287,
 288,
 290,
 291,
 292,
 294,
 296,
 299,
 300,
 301,
 303,
 304,
 306,
 312,
 314,
 317,
 318,
 320,
 323,
 326,
 329,
 330,
 331,
 334,
 335,
 337,
 338,
 340,
 341,
 344,
 345,
 347,
 348,
 349,
 350,
 351,
 353,
 354,
 358,
 359,
 360,
 362,
 363,
 367,
 368,
 373,
 374,
 375,
 376,
 378,
 379,
 381,
 382,
 383,
 384,
 390,
 392,
 393,
 394,
 401,
 402,
 404,
 406,
 407,
 408,
 409,
 411,
 412,
 416,
 417,
 420,
 421,
 423,
 424,
 425,
 428,
 429,
 430,
 433,
 438,
 439,
 442,
 444,
 446,
 450,
 452,
 453,
 454,
 455,
 456,
 459,
 460,
 461,
 464,
 466,
 468,
 469,
 471,
 472,
 473,
 475,
 476,
 477,
 479,
 481,
 482,
 484,
 486,
 491,
 492,
 494,
 498,
 503,
 507,
 508,
 510,
 511,
 512,
 514,
 517,
 518,
 519,
 520,
 523,
 524,
 526,
 530,
 534,
 537,
 539,
 541,
 544,
 545,
 548,
 553,
 555,
 556,
 559,
 561,
 564,
 565,
 566,
 567,
 569,
 570,
 572,
 574,
 575,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 585,
 586,
 591,
 593,
 594,
 595,
 596,
 598,
 602,
 603,
 604,
 606,
 608,
 612,
 614,
 615,
 618,
 619,
 620,
 621,
 623,
 626,
 628,
 629,
 632,
 634,
 635,
 636,
 639,
 640,
 641,
 643,
 646,
 647,
 653,
 654,
 657,
 659,
 660,
 661,
 662,
 663,
 667,
 674,
 675,
 676,
 677,
 678,
 679,
 684,
 685,
 686,
 687,
 688,
 693,
 695,
 696,
 697,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 713,
 714,
 715,
 718,
 719,
 721,
 723,
 724,
 725,
 726,
 727,
 728,
 732,
 733,
 734,
 735,
 737,
 739,
 740,
 742,
 743,
 746,
 747,
 749,
 750,
 751,
 752,
 753,
 755,
 760,
 762,
 766,
 768,
 770,
 771,
 775,
 778,
 779,
 780,
 787,
 789,
 790,
 793,
 794,
 795,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 809,
 810,
 811,
 814,
 818,
 822,
 823,
 826,
 827,
 829,
 833,
 835,
 837,
 839,
 843,
 844,
 846,
 847,
 848,
 849,
 851,
 852,
 855,
 859,
 862,
 867,
 869,
 870,
 874,
 875,
 876,
 877,
 878,
 880,
 881,
 882,
 883,
 888,
 889,
 890,
 891,
 892,
 893,
 897,
 899,
 901,
 904,
 905,
 908,
 909,
 913,
 917,
 922,
 923,
 924,
 925,
 926,
 929,
 932,
 940,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 950,
 952,
 953,
 954,
 955,
 956,
 957,
 960,
 964,
 968,
 969,
 970,
 971,
 975,
 976,
 977,
 978,
 980,
 981,
 983,
 985,
 986,
 987,
 991,
 993,
 994,
 999,
 1010,
 1012,
 1014,
 1015,
 1017,
 1020,
 1021,
 1022,
 1023,
 1025,
 1027,
 1028,
 1030,
 1032,
 1034,
 1038,
 1039,
 1041,
 1042,
 1047,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1057,
 1060,
 1061,
 1063,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 1070,
 1074,
 1077,
 1080,
 1082,
 1089,
 1090,
 1096,
 1099,
 1100,
 1101,
 1104,
 1106,
 1107,
 1109,
 1112,
 1114,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1127,
 1128,
 1131,
 1132,
 1133,
 1138,
 1140,
 1143,
 1144,
 1147,
 1149,
 1151,
 1152,
 1153,
 1154,
 1158,
 1159,
 1162,
 1169,
 1173,
 1174,
 1175,
 1176,
 1178,
 1183,
 1184,
 1186,
 1187,
 1189,
 1190,
 1191,
 1192,
 1197,
 1198,
 1204,
 1208,
 1212,
 1213,
 1215,
 1217,
 1218,
 1220,
 1223,
 1224,
 1228,
 1229,
 1230,
 1231,
 1232,
 1233,
 1234,
 1237,
 1238,
 1239,
 1240,
 1241,
 1242,
 1243,
 1246,
 1247,
 1248,
 1249,
 1252,
 1255,
 1257,
 1261,
 1262,
 1263,
 1266,
 1267,
 1268,
 1269,
 1273,
 1274,
 1275,
 1276,
 1278,
 1279,
 1280,
 1283,
 1285,
 1287,
 1296,
 1297,
 1298,
 1299,
 1302,
 1303,
 1304,
 1305,
 1308,
 1311,
 1314,
 1316,
 1318,
 1319,
 1322,
 1324,
 1325,
 1327,
 1328,
 1329,
 1330,
 1332,
 1334,
 1335,
 1336,
 1337,
 1339,
 1343,
 1344,
 1346,
 1349,
 1352,
 1353,
 1354,
 1355,
 1357,
 1359,
 1364,
 1365,
 1366,
 1367,
 1369,
 1371,
 1372,
 1374,
 1376,
 1378,
 1381,
 1384,
 1385,
 1386,
 1388,
 1389,
 1390,
 1391,
 1392,
 1394,
 1395,
 1398,
 1401,
 1403,
 1406,
 1408,
 1410,
 1413,
 1414,
 1416,
 1417,
 1418,
 1419,
 1424,
 1425,
 1426,
 1428,
 1430,
 1431,
 1432,
 1433,
 1436,
 1441,
 1442,
 1443,
 1445,
 1447,
 1450,
 1451,
 1452,
 1453,
 1454,
 1456,
 1461,
 1464,
 1465,
 1467,
 1469,
 1470,
 1471,
 1472,
 1473,
 1474,
 1480,
 1482,
 1483,
 1484,
 1487,
 1488,
 1490,
 1492,
 1493,
 1495,
 1501,
 1502,
 1503,
 1504,
 1506,
 1509,
 1511,
 1514,
 1515,
 1516,
 1517,
 1518,
 1520,
 1521,
 1522,
 1525,
 1527,
 1529,
 1537,
 1540,
 1541,
 1542,
 1545,
 1546,
 1550,
 1552,
 1553,
 1555,
 1559,
 1560,
 1562,
 1563,
 1564,
 1565,
 1567,
 1568,
 1569,
 1570,
 1573,
 1575,
 1576,
 1579,
 1580,
 1584,
 1585,
 1586,
 1587,
 1589,
 1592,
 1595,
 1597,
 1598,
 1599,
 1602,
 1606,
 1608,
 1611,
 1612,
 1615,
 1618,
 1621,
 1622,
 1624,
 1625,
 1629,
 1630,
 1632,
 1633,
 1634,
 1635,
 1636,
 1641,
 1643,
 1647,
 1651,
 1652,
 1653,
 1654,
 1655,
 1656,
 1659,
 1660,
 1662,
 1665,
 1666,
 1668,
 1670,
 1671,
 1672,
 1673,
 1676,
 1678,
 1679,
 1681,
 1682,
 1683,
 1687,
 1688,
 1691,
 1692,
 1694,
 1696,
 1697,
 1700,
 1701,
 1702,
 1705,
 1709,
 1710,
 1711,
 1716,
 1720,
 1722,
 1724,
 1726,
 1727,
 1730,
 1732,
 1733,
 1734,
 1737,
 1738,
 1739,
 1740,
 1743,
 1744,
 1745,
 1747,
 1751,
 1752,
 1755,
 1756,
 1758,
 1759,
 1761,
 1762,
 1763,
 1764,
 1767,
 1769,
 1771,
 1773,
 1774,
 1775,
 1776,
 1778,
 1780,
 1781,
 1782,
 1783,
 1784,
 1785,
 1786,
 1791,
 1793,
 1795,
 1796,
 1798,
 1799,
 1800,
 1801,
 1802,
 1803,
 1804,
 1810,
 1816,
 1817,
 1818,
 1819,
 1821,
 1824,
 1828,
 1829,
 1830,
 1831,
 1833,
 1834,
 1838,
 1844,
 1849,
 1851,
 1854,
 1856,
 1857,
 1859,
 1861,
 1862,
 1864,
 1866,
 1867,
 1869,
 1870,
 1873,
 1876,
 1877,
 1880,
 1882,
 1887,
 1894,
 1895,
 1897,
 1898,
 1908,
 1909,
 1911,
 1912,
 1913,
 1916,
 1918,
 1920,
 1921,
 1923,
 1924,
 1925,
 1926,
 1927,
 1928,
 1929,
 1932,
 1936,
 1938,
 1939,
 1941,
 1944,
 1947,
 1948,
 1949,
 1950,
 1951,
 1954,
 1956,
 1957,
 1959,
 ...]

In [213]:


def semi_sup(S, masked, W_f, attention_wts, device = device):

    grad_semi = torch.zeros_like(S, device=device)
    
    for i in masked:
        neighbors_list = W_f[i]
        
        if not neighbors_list:
            continue
            
        w_ij = attention_wts[i]
        
        neighbors_idx = torch.tensor(neighbors_list, dtype=torch.long, device=S.device)
        S_j = S[neighbors_idx]
        
        weighted_sum = (w_ij.unsqueeze(1) * S_j).sum(dim=0)
        

        grad_semi[i] = S[i] - weighted_sum
        
    return grad_semi

In [214]:
# optimization loop :
lr = 0.31
lambda_sup = 0.6
lambda_semi = 1.9


for i in range(200):
    
    wij = attention_wts(W_f, S)
    
    Q_semi = semi_sup(S, masked, W_f, wij)
    Q_prop = modularity(A, edgelist, S)
    Q_sup = sup_reg(S, labels_list)
    
    S = S - lr*(Q_prop - lambda_sup*Q_sup - lambda_semi*Q_semi)
    
    Q, R = torch.linalg.qr(S)
    S = Q
    print(f"Iteration {i+1} completed.")

Iteration 1 completed.
Iteration 2 completed.
Iteration 3 completed.
Iteration 4 completed.
Iteration 5 completed.
Iteration 6 completed.
Iteration 7 completed.
Iteration 8 completed.
Iteration 9 completed.
Iteration 10 completed.
Iteration 11 completed.
Iteration 12 completed.
Iteration 13 completed.
Iteration 14 completed.
Iteration 15 completed.
Iteration 16 completed.
Iteration 17 completed.
Iteration 18 completed.
Iteration 19 completed.
Iteration 20 completed.
Iteration 21 completed.
Iteration 22 completed.
Iteration 23 completed.
Iteration 24 completed.
Iteration 25 completed.
Iteration 26 completed.
Iteration 27 completed.
Iteration 28 completed.
Iteration 29 completed.
Iteration 30 completed.
Iteration 31 completed.
Iteration 32 completed.
Iteration 33 completed.
Iteration 34 completed.
Iteration 35 completed.
Iteration 36 completed.
Iteration 37 completed.
Iteration 38 completed.
Iteration 39 completed.
Iteration 40 completed.
Iteration 41 completed.
Iteration 42 completed.
Iteration 43 completed.
Iteration 44 completed.
Iteration 45 completed.
Iteration 46 completed.
Iteration 47 completed.
Iteration 48 completed.
Iteration 49 completed.
Iteration 50 completed.
Iteration 51 completed.
Iteration 52 completed.
Iteration 53 completed.
Iteration 54 completed.
Iteration 55 completed.
Iteration 56 completed.
Iteration 57 completed.
Iteration 58 completed.
Iteration 59 completed.
Iteration 60 completed.
Iteration 61 completed.
Iteration 62 completed.
Iteration 63 completed.
Iteration 64 completed.
Iteration 65 completed.
Iteration 66 completed.
Iteration 67 completed.
Iteration 68 completed.
Iteration 69 completed.
Iteration 70 completed.
Iteration 71 completed.
Iteration 72 completed.
Iteration 73 completed.
Iteration 74 completed.
Iteration 75 completed.
Iteration 76 completed.
Iteration 77 completed.
Iteration 78 completed.
Iteration 79 completed.
Iteration 80 completed.
Iteration 81 completed.
Iteration 82 completed.
Iteration 83 completed.
Iteration 84 completed.
Iteration 85 completed.
Iteration 86 completed.
Iteration 87 completed.
Iteration 88 completed.
Iteration 89 completed.
Iteration 90 completed.
Iteration 91 completed.
Iteration 92 completed.
Iteration 93 completed.
Iteration 94 completed.
Iteration 95 completed.
Iteration 96 completed.
Iteration 97 completed.
Iteration 98 completed.
Iteration 99 completed.
Iteration 100 completed.
Iteration 101 completed.
Iteration 102 completed.
Iteration 103 completed.
Iteration 104 completed.
Iteration 105 completed.
Iteration 106 completed.
Iteration 107 completed.
Iteration 108 completed.
Iteration 109 completed.
Iteration 110 completed.
Iteration 111 completed.
Iteration 112 completed.
Iteration 113 completed.
Iteration 114 completed.
Iteration 115 completed.
Iteration 116 completed.
Iteration 117 completed.
Iteration 118 completed.
Iteration 119 completed.
Iteration 120 completed.
Iteration 121 completed.
Iteration 122 completed.
Iteration 123 completed.
Iteration 124 completed.
Iteration 125 completed.
Iteration 126 completed.
Iteration 127 completed.
Iteration 128 completed.
Iteration 129 completed.
Iteration 130 completed.
Iteration 131 completed.
Iteration 132 completed.
Iteration 133 completed.
Iteration 134 completed.
Iteration 135 completed.
Iteration 136 completed.
Iteration 137 completed.
Iteration 138 completed.
Iteration 139 completed.
Iteration 140 completed.
Iteration 141 completed.
Iteration 142 completed.
Iteration 143 completed.
Iteration 144 completed.
Iteration 145 completed.
Iteration 146 completed.
Iteration 147 completed.
Iteration 148 completed.
Iteration 149 completed.
Iteration 150 completed.
Iteration 151 completed.
Iteration 152 completed.
Iteration 153 completed.
Iteration 154 completed.
Iteration 155 completed.
Iteration 156 completed.
Iteration 157 completed.
Iteration 158 completed.
Iteration 159 completed.
Iteration 160 completed.
Iteration 161 completed.
Iteration 162 completed.
Iteration 163 completed.
Iteration 164 completed.
Iteration 165 completed.
Iteration 166 completed.
Iteration 167 completed.
Iteration 168 completed.
Iteration 169 completed.
Iteration 170 completed.
Iteration 171 completed.
Iteration 172 completed.
Iteration 173 completed.
Iteration 174 completed.
Iteration 175 completed.
Iteration 176 completed.
Iteration 177 completed.
Iteration 178 completed.
Iteration 179 completed.
Iteration 180 completed.
Iteration 181 completed.
Iteration 182 completed.
Iteration 183 completed.
Iteration 184 completed.
Iteration 185 completed.
Iteration 186 completed.
Iteration 187 completed.
Iteration 188 completed.
Iteration 189 completed.
Iteration 190 completed.
Iteration 191 completed.
Iteration 192 completed.
Iteration 193 completed.
Iteration 194 completed.
Iteration 195 completed.
Iteration 196 completed.
Iteration 197 completed.
Iteration 198 completed.
Iteration 199 completed.
Iteration 200 completed.

In [215]:
S
torch.save(S, 'S_cora.pt')  # Saves tensor to 'tensor.pt' in the current directory

### Training MLP for the node classification: S_generated

In [ ]:
# train test split :


S_generated = torch.load('S_cora.pt')  

S_train = S_generated[labels_masked != -1]
S_test = S_generated[labels_masked == -1]

C:\Users\mehul\AppData\Local\Temp\ipykernel_19796\2835061828.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  S_generated = torch.load('S_cora.pt')

In [217]:
S_train.shape

torch.Size([1354, 145])

In [218]:
S_test.shape

torch.Size([1354, 145])

In [221]:
labels_train = labels_masked[labels_masked != -1]
labels_train.shape

torch.Size([1354])

In [226]:
import torch
import torch.nn as nn
import torch.optim as optim

class smol_mp(nn.Module):
    def __init__(self, input_dim, layers=[256, 128, 64, 32], num_classes=7):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, layers[0]),
            nn.ReLU(),
            nn.Linear(layers[0], layers[1]),
            nn.ReLU(),
            nn.Linear(layers[1], layers[2]),
            nn.ReLU(),
            nn.Linear(layers[2], layers[3]),
            nn.ReLU(),
            nn.Linear(layers[3], num_classes)
        )

    def forward(self, x):
        return self.net(x)
    

smol1 = smol_mp(input_dim=145) 

labels_train = labels_train.clone().detach().long()# CrossEntropy expects Long type
S = S_generated

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(smol1.parameters(), lr= 0.01)

epochs = 10000
smol1.train() 

for epoch in range(epochs):
    optimizer.zero_grad()                     
    
    logits_train = smol1(S_train)              
    loss = criterion(logits_train, labels_train) 
    
    loss.backward()                            
    optimizer.step()                           
    
    # Optional: Print progress
    if (epoch + 1) % 2 == 0:
        print(f"Epoch {epoch + 1}/{epochs} | Loss: {loss.item():.4f}")

Epoch 2/10000 | Loss: 1.9222
Epoch 4/10000 | Loss: 1.8679
Epoch 6/10000 | Loss: 1.8501
Epoch 8/10000 | Loss: 1.8193
Epoch 10/10000 | Loss: 1.8302
Epoch 12/10000 | Loss: 1.8254
Epoch 14/10000 | Loss: 1.8173
Epoch 16/10000 | Loss: 1.8196
Epoch 18/10000 | Loss: 1.8167
Epoch 20/10000 | Loss: 1.8168
Epoch 22/10000 | Loss: 1.8173
Epoch 24/10000 | Loss: 1.8159
Epoch 26/10000 | Loss: 1.8158
Epoch 28/10000 | Loss: 1.8162
Epoch 30/10000 | Loss: 1.8155
Epoch 32/10000 | Loss: 1.8155
Epoch 34/10000 | Loss: 1.8155
Epoch 36/10000 | Loss: 1.8152
Epoch 38/10000 | Loss: 1.8153
Epoch 40/10000 | Loss: 1.8154
Epoch 42/10000 | Loss: 1.8152
Epoch 44/10000 | Loss: 1.8152
Epoch 46/10000 | Loss: 1.8152
Epoch 48/10000 | Loss: 1.8151
Epoch 50/10000 | Loss: 1.8152
Epoch 52/10000 | Loss: 1.8152
Epoch 54/10000 | Loss: 1.8151
Epoch 56/10000 | Loss: 1.8151
Epoch 58/10000 | Loss: 1.8151
Epoch 60/10000 | Loss: 1.8151
Epoch 62/10000 | Loss: 1.8151
Epoch 64/10000 | Loss: 1.8151
Epoch 66/10000 | Loss: 1.8151
Epoch 68/10000 | Loss: 1.8151
Epoch 70/10000 | Loss: 1.8151
Epoch 72/10000 | Loss: 1.8151
Epoch 74/10000 | Loss: 1.8151
Epoch 76/10000 | Loss: 1.8151
Epoch 78/10000 | Loss: 1.8151
Epoch 80/10000 | Loss: 1.8151
Epoch 82/10000 | Loss: 1.8151
Epoch 84/10000 | Loss: 1.8151
Epoch 86/10000 | Loss: 1.8151
Epoch 88/10000 | Loss: 1.8151
Epoch 90/10000 | Loss: 1.8151
Epoch 92/10000 | Loss: 1.8151
Epoch 94/10000 | Loss: 1.8151
Epoch 96/10000 | Loss: 1.8151
Epoch 98/10000 | Loss: 1.8151
Epoch 100/10000 | Loss: 1.8151
Epoch 102/10000 | Loss: 1.8151
Epoch 104/10000 | Loss: 1.8151
Epoch 106/10000 | Loss: 1.8151
Epoch 108/10000 | Loss: 1.8151
Epoch 110/10000 | Loss: 1.8151
Epoch 112/10000 | Loss: 1.8151
Epoch 114/10000 | Loss: 1.8151
Epoch 116/10000 | Loss: 1.8151
Epoch 118/10000 | Loss: 1.8151
Epoch 120/10000 | Loss: 1.8151
Epoch 122/10000 | Loss: 1.8151
Epoch 124/10000 | Loss: 1.8151
Epoch 126/10000 | Loss: 1.8151
Epoch 128/10000 | Loss: 1.8151
Epoch 130/10000 | Loss: 1.8151
Epoch 132/10000 | Loss: 1.8151
Epoch 134/10000 | Loss: 1.8151
Epoch 136/10000 | Loss: 1.8151
Epoch 138/10000 | Loss: 1.8151
Epoch 140/10000 | Loss: 1.8151
Epoch 142/10000 | Loss: 1.8151
Epoch 144/10000 | Loss: 1.8151
Epoch 146/10000 | Loss: 1.8151
Epoch 148/10000 | Loss: 1.8151
Epoch 150/10000 | Loss: 1.8151
Epoch 152/10000 | Loss: 1.8151
Epoch 154/10000 | Loss: 1.8151
Epoch 156/10000 | Loss: 1.8151
Epoch 158/10000 | Loss: 1.8151
Epoch 160/10000 | Loss: 1.8151
Epoch 162/10000 | Loss: 1.8151
Epoch 164/10000 | Loss: 1.8151
Epoch 166/10000 | Loss: 1.8151
Epoch 168/10000 | Loss: 1.8151
Epoch 170/10000 | Loss: 1.8151
Epoch 172/10000 | Loss: 1.8151
Epoch 174/10000 | Loss: 1.8151
Epoch 176/10000 | Loss: 1.8151
Epoch 178/10000 | Loss: 1.8151
Epoch 180/10000 | Loss: 1.8151
Epoch 182/10000 | Loss: 1.8151
Epoch 184/10000 | Loss: 1.8151
Epoch 186/10000 | Loss: 1.8151
Epoch 188/10000 | Loss: 1.8151
Epoch 190/10000 | Loss: 1.8151
Epoch 192/10000 | Loss: 1.8151
Epoch 194/10000 | Loss: 1.8151
Epoch 196/10000 | Loss: 1.8151
Epoch 198/10000 | Loss: 1.8151
Epoch 200/10000 | Loss: 1.8151
Epoch 202/10000 | Loss: 1.8151
Epoch 204/10000 | Loss: 1.8151
Epoch 206/10000 | Loss: 1.8151
Epoch 208/10000 | Loss: 1.8151
Epoch 210/10000 | Loss: 1.8151
Epoch 212/10000 | Loss: 1.8151
Epoch 214/10000 | Loss: 1.8151
Epoch 216/10000 | Loss: 1.8151
Epoch 218/10000 | Loss: 1.8151
Epoch 220/10000 | Loss: 1.8151
Epoch 222/10000 | Loss: 1.8151
Epoch 224/10000 | Loss: 1.8151
Epoch 226/10000 | Loss: 1.8151
Epoch 228/10000 | Loss: 1.8151
Epoch 230/10000 | Loss: 1.8151
Epoch 232/10000 | Loss: 1.8151
Epoch 234/10000 | Loss: 1.8151
Epoch 236/10000 | Loss: 1.8151
Epoch 238/10000 | Loss: 1.8151
Epoch 240/10000 | Loss: 1.8151
Epoch 242/10000 | Loss: 1.8151
Epoch 244/10000 | Loss: 1.8151
Epoch 246/10000 | Loss: 1.8151
Epoch 248/10000 | Loss: 1.8151
Epoch 250/10000 | Loss: 1.8151
Epoch 252/10000 | Loss: 1.8151
Epoch 254/10000 | Loss: 1.8151
Epoch 256/10000 | Loss: 1.8151
Epoch 258/10000 | Loss: 1.8151
Epoch 260/10000 | Loss: 1.8151
Epoch 262/10000 | Loss: 1.8151
Epoch 264/10000 | Loss: 1.8151
Epoch 266/10000 | Loss: 1.8151
Epoch 268/10000 | Loss: 1.8151
Epoch 270/10000 | Loss: 1.8151
Epoch 272/10000 | Loss: 1.8151
Epoch 274/10000 | Loss: 1.8151
Epoch 276/10000 | Loss: 1.8151
Epoch 278/10000 | Loss: 1.8151
Epoch 280/10000 | Loss: 1.8151
Epoch 282/10000 | Loss: 1.8151
Epoch 284/10000 | Loss: 1.8151
Epoch 286/10000 | Loss: 1.8151
Epoch 288/10000 | Loss: 1.8151
Epoch 290/10000 | Loss: 1.8151
Epoch 292/10000 | Loss: 1.8151
Epoch 294/10000 | Loss: 1.8151
Epoch 296/10000 | Loss: 1.8151
Epoch 298/10000 | Loss: 1.8151
Epoch 300/10000 | Loss: 1.8151
Epoch 302/10000 | Loss: 1.8151
Epoch 304/10000 | Loss: 1.8151
Epoch 306/10000 | Loss: 1.8151
Epoch 308/10000 | Loss: 1.8151
Epoch 310/10000 | Loss: 1.8151
Epoch 312/10000 | Loss: 1.8151
Epoch 314/10000 | Loss: 1.8151
Epoch 316/10000 | Loss: 1.8151
Epoch 318/10000 | Loss: 1.8151
Epoch 320/10000 | Loss: 1.8151
Epoch 322/10000 | Loss: 1.8151
Epoch 324/10000 | Loss: 1.8151
Epoch 326/10000 | Loss: 1.8151
Epoch 328/10000 | Loss: 1.8151
Epoch 330/10000 | Loss: 1.8151
Epoch 332/10000 | Loss: 1.8151
Epoch 334/10000 | Loss: 1.8151
Epoch 336/10000 | Loss: 1.8151
Epoch 338/10000 | Loss: 1.8151
Epoch 340/10000 | Loss: 1.8151
Epoch 342/10000 | Loss: 1.8151
Epoch 344/10000 | Loss: 1.8151
Epoch 346/10000 | Loss: 1.8151
Epoch 348/10000 | Loss: 1.8151
Epoch 350/10000 | Loss: 1.8151
Epoch 352/10000 | Loss: 1.8151
Epoch 354/10000 | Loss: 1.8151
Epoch 356/10000 | Loss: 1.8151
Epoch 358/10000 | Loss: 1.8150
Epoch 360/10000 | Loss: 1.8150
Epoch 362/10000 | Loss: 1.8150
Epoch 364/10000 | Loss: 1.8150
Epoch 366/10000 | Loss: 1.8150
Epoch 368/10000 | Loss: 1.8150
Epoch 370/10000 | Loss: 1.8150
Epoch 372/10000 | Loss: 1.8150
Epoch 374/10000 | Loss: 1.8150
Epoch 376/10000 | Loss: 1.8150
Epoch 378/10000 | Loss: 1.8150
Epoch 380/10000 | Loss: 1.8150
Epoch 382/10000 | Loss: 1.8150
Epoch 384/10000 | Loss: 1.8150
Epoch 386/10000 | Loss: 1.8150
Epoch 388/10000 | Loss: 1.8150
Epoch 390/10000 | Loss: 1.8150
Epoch 392/10000 | Loss: 1.8150
Epoch 394/10000 | Loss: 1.8150
Epoch 396/10000 | Loss: 1.8150
Epoch 398/10000 | Loss: 1.8150
Epoch 400/10000 | Loss: 1.8150
Epoch 402/10000 | Loss: 1.8150
Epoch 404/10000 | Loss: 1.8150
Epoch 406/10000 | Loss: 1.8150
Epoch 408/10000 | Loss: 1.8150
Epoch 410/10000 | Loss: 1.8150
Epoch 412/10000 | Loss: 1.8150
Epoch 414/10000 | Loss: 1.8150
Epoch 416/10000 | Loss: 1.8150
Epoch 418/10000 | Loss: 1.8150
Epoch 420/10000 | Loss: 1.8150
Epoch 422/10000 | Loss: 1.8150
Epoch 424/10000 | Loss: 1.8150
Epoch 426/10000 | Loss: 1.8150
Epoch 428/10000 | Loss: 1.8150
Epoch 430/10000 | Loss: 1.8150
Epoch 432/10000 | Loss: 1.8150
Epoch 434/10000 | Loss: 1.8150
Epoch 436/10000 | Loss: 1.8150
Epoch 438/10000 | Loss: 1.8150
Epoch 440/10000 | Loss: 1.8150
Epoch 442/10000 | Loss: 1.8150
Epoch 444/10000 | Loss: 1.8150
Epoch 446/10000 | Loss: 1.8150
Epoch 448/10000 | Loss: 1.8150
Epoch 450/10000 | Loss: 1.8150
Epoch 452/10000 | Loss: 1.8150
Epoch 454/10000 | Loss: 1.8150
Epoch 456/10000 | Loss: 1.8150
Epoch 458/10000 | Loss: 1.8150
Epoch 460/10000 | Loss: 1.8150
Epoch 462/10000 | Loss: 1.8150
Epoch 464/10000 | Loss: 1.8150
Epoch 466/10000 | Loss: 1.8150
Epoch 468/10000 | Loss: 1.8150
Epoch 470/10000 | Loss: 1.8150
Epoch 472/10000 | Loss: 1.8150
Epoch 474/10000 | Loss: 1.8150
Epoch 476/10000 | Loss: 1.8150
Epoch 478/10000 | Loss: 1.8150
Epoch 480/10000 | Loss: 1.8150
Epoch 482/10000 | Loss: 1.8150
Epoch 484/10000 | Loss: 1.8150
Epoch 486/10000 | Loss: 1.8150
Epoch 488/10000 | Loss: 1.8150
Epoch 490/10000 | Loss: 1.8150
Epoch 492/10000 | Loss: 1.8149
Epoch 494/10000 | Loss: 1.8149
Epoch 496/10000 | Loss: 1.8149
Epoch 498/10000 | Loss: 1.8149
Epoch 500/10000 | Loss: 1.8149
Epoch 502/10000 | Loss: 1.8149
Epoch 504/10000 | Loss: 1.8149
Epoch 506/10000 | Loss: 1.8149
Epoch 508/10000 | Loss: 1.8149
Epoch 510/10000 | Loss: 1.8149
Epoch 512/10000 | Loss: 1.8149
Epoch 514/10000 | Loss: 1.8149
Epoch 516/10000 | Loss: 1.8149
Epoch 518/10000 | Loss: 1.8149
Epoch 520/10000 | Loss: 1.8149
Epoch 522/10000 | Loss: 1.8149
Epoch 524/10000 | Loss: 1.8149
Epoch 526/10000 | Loss: 1.8149
Epoch 528/10000 | Loss: 1.8148
Epoch 530/10000 | Loss: 1.8148
Epoch 532/10000 | Loss: 1.8148
Epoch 534/10000 | Loss: 1.8148
Epoch 536/10000 | Loss: 1.8148
Epoch 538/10000 | Loss: 1.8148
Epoch 540/10000 | Loss: 1.8148
Epoch 542/10000 | Loss: 1.8148
Epoch 544/10000 | Loss: 1.8148
Epoch 546/10000 | Loss: 1.8148
Epoch 548/10000 | Loss: 1.8155
Epoch 550/10000 | Loss: 1.8151
Epoch 552/10000 | Loss: 1.8149
Epoch 554/10000 | Loss: 1.8151
Epoch 556/10000 | Loss: 1.8151
Epoch 558/10000 | Loss: 1.8150
Epoch 560/10000 | Loss: 1.8149
Epoch 562/10000 | Loss: 1.8149
Epoch 564/10000 | Loss: 1.8150
Epoch 566/10000 | Loss: 1.8149
Epoch 568/10000 | Loss: 1.8149
Epoch 570/10000 | Loss: 1.8149
Epoch 572/10000 | Loss: 1.8149
Epoch 574/10000 | Loss: 1.8149
Epoch 576/10000 | Loss: 1.8148
Epoch 578/10000 | Loss: 1.8149
Epoch 580/10000 | Loss: 1.8149
Epoch 582/10000 | Loss: 1.8148
Epoch 584/10000 | Loss: 1.8148
Epoch 586/10000 | Loss: 1.8148
Epoch 588/10000 | Loss: 1.8148
Epoch 590/10000 | Loss: 1.8148
Epoch 592/10000 | Loss: 1.8148
Epoch 594/10000 | Loss: 1.8148
Epoch 596/10000 | Loss: 1.8148
Epoch 598/10000 | Loss: 1.8152
Epoch 600/10000 | Loss: 1.8160
Epoch 602/10000 | Loss: 1.8158
Epoch 604/10000 | Loss: 1.8151
Epoch 606/10000 | Loss: 1.8148
Epoch 608/10000 | Loss: 1.8148
Epoch 610/10000 | Loss: 1.8149
Epoch 612/10000 | Loss: 1.8149
Epoch 614/10000 | Loss: 1.8149
Epoch 616/10000 | Loss: 1.8149
Epoch 618/10000 | Loss: 1.8149
Epoch 620/10000 | Loss: 1.8149
Epoch 622/10000 | Loss: 1.8149
Epoch 624/10000 | Loss: 1.8149
Epoch 626/10000 | Loss: 1.8149
Epoch 628/10000 | Loss: 1.8149
Epoch 630/10000 | Loss: 1.8149
Epoch 632/10000 | Loss: 1.8148
Epoch 634/10000 | Loss: 1.8148
Epoch 636/10000 | Loss: 1.8148
Epoch 638/10000 | Loss: 1.8148
Epoch 640/10000 | Loss: 1.8148
Epoch 642/10000 | Loss: 1.8148
Epoch 644/10000 | Loss: 1.8148
Epoch 646/10000 | Loss: 1.8147
Epoch 648/10000 | Loss: 1.8147
Epoch 650/10000 | Loss: 1.8147
Epoch 652/10000 | Loss: 1.8147
Epoch 654/10000 | Loss: 1.8147
Epoch 656/10000 | Loss: 1.8147
Epoch 658/10000 | Loss: 1.8146
Epoch 660/10000 | Loss: 1.8146
Epoch 662/10000 | Loss: 1.8146
Epoch 664/10000 | Loss: 1.8146
Epoch 666/10000 | Loss: 1.8146
Epoch 668/10000 | Loss: 1.8153
Epoch 670/10000 | Loss: 1.8153
Epoch 672/10000 | Loss: 1.8162
Epoch 674/10000 | Loss: 1.8162
Epoch 676/10000 | Loss: 1.8155
Epoch 678/10000 | Loss: 1.8151
Epoch 680/10000 | Loss: 1.8150
Epoch 682/10000 | Loss: 1.8149
Epoch 684/10000 | Loss: 1.8149
Epoch 686/10000 | Loss: 1.8149
Epoch 688/10000 | Loss: 1.8149
Epoch 690/10000 | Loss: 1.8149
Epoch 692/10000 | Loss: 1.8149
Epoch 694/10000 | Loss: 1.8149
Epoch 696/10000 | Loss: 1.8148
Epoch 698/10000 | Loss: 1.8148
Epoch 700/10000 | Loss: 1.8148
Epoch 702/10000 | Loss: 1.8148
Epoch 704/10000 | Loss: 1.8147
Epoch 706/10000 | Loss: 1.8147
Epoch 708/10000 | Loss: 1.8147
Epoch 710/10000 | Loss: 1.8147
Epoch 712/10000 | Loss: 1.8146
Epoch 714/10000 | Loss: 1.8146
Epoch 716/10000 | Loss: 1.8146
Epoch 718/10000 | Loss: 1.8146
Epoch 720/10000 | Loss: 1.8145
Epoch 722/10000 | Loss: 1.8145
Epoch 724/10000 | Loss: 1.8145
Epoch 726/10000 | Loss: 1.8144
Epoch 728/10000 | Loss: 1.8144
Epoch 730/10000 | Loss: 1.8144
Epoch 732/10000 | Loss: 1.8143
Epoch 734/10000 | Loss: 1.8144
Epoch 736/10000 | Loss: 1.8167
Epoch 738/10000 | Loss: 1.8240
Epoch 740/10000 | Loss: 1.8191
Epoch 742/10000 | Loss: 1.8158
Epoch 744/10000 | Loss: 1.8156
Epoch 746/10000 | Loss: 1.8170
Epoch 748/10000 | Loss: 1.8153
Epoch 750/10000 | Loss: 1.8156
Epoch 752/10000 | Loss: 1.8155
Epoch 754/10000 | Loss: 1.8149
Epoch 756/10000 | Loss: 1.8155
Epoch 758/10000 | Loss: 1.8148
Epoch 760/10000 | Loss: 1.8153
Epoch 762/10000 | Loss: 1.8149
Epoch 764/10000 | Loss: 1.8151
Epoch 766/10000 | Loss: 1.8149
Epoch 768/10000 | Loss: 1.8150
Epoch 770/10000 | Loss: 1.8149
Epoch 772/10000 | Loss: 1.8149
Epoch 774/10000 | Loss: 1.8149
Epoch 776/10000 | Loss: 1.8149
Epoch 778/10000 | Loss: 1.8149
Epoch 780/10000 | Loss: 1.8149
Epoch 782/10000 | Loss: 1.8149
Epoch 784/10000 | Loss: 1.8148
Epoch 786/10000 | Loss: 1.8149
Epoch 788/10000 | Loss: 1.8148
Epoch 790/10000 | Loss: 1.8148
Epoch 792/10000 | Loss: 1.8148
Epoch 794/10000 | Loss: 1.8148
Epoch 796/10000 | Loss: 1.8148
Epoch 798/10000 | Loss: 1.8148
Epoch 800/10000 | Loss: 1.8148
Epoch 802/10000 | Loss: 1.8148
Epoch 804/10000 | Loss: 1.8148
Epoch 806/10000 | Loss: 1.8148
Epoch 808/10000 | Loss: 1.8148
Epoch 810/10000 | Loss: 1.8147
Epoch 812/10000 | Loss: 1.8147
Epoch 814/10000 | Loss: 1.8147
Epoch 816/10000 | Loss: 1.8147
Epoch 818/10000 | Loss: 1.8147
Epoch 820/10000 | Loss: 1.8147
Epoch 822/10000 | Loss: 1.8147
Epoch 824/10000 | Loss: 1.8147
Epoch 826/10000 | Loss: 1.8146
Epoch 828/10000 | Loss: 1.8146
Epoch 830/10000 | Loss: 1.8146
Epoch 832/10000 | Loss: 1.8146
Epoch 834/10000 | Loss: 1.8146
Epoch 836/10000 | Loss: 1.8146
Epoch 838/10000 | Loss: 1.8145
Epoch 840/10000 | Loss: 1.8145
Epoch 842/10000 | Loss: 1.8145
Epoch 844/10000 | Loss: 1.8145
Epoch 846/10000 | Loss: 1.8144
Epoch 848/10000 | Loss: 1.8144
Epoch 850/10000 | Loss: 1.8144
Epoch 852/10000 | Loss: 1.8143
Epoch 854/10000 | Loss: 1.8143
Epoch 856/10000 | Loss: 1.8143
Epoch 858/10000 | Loss: 1.8142
Epoch 860/10000 | Loss: 1.8142
Epoch 862/10000 | Loss: 1.8141
Epoch 864/10000 | Loss: 1.8140
Epoch 866/10000 | Loss: 1.8140
Epoch 868/10000 | Loss: 1.8139
Epoch 870/10000 | Loss: 1.8138
Epoch 872/10000 | Loss: 1.8137
Epoch 874/10000 | Loss: 1.8136
Epoch 876/10000 | Loss: 1.8135
Epoch 878/10000 | Loss: 1.8134
Epoch 880/10000 | Loss: 1.8137
Epoch 882/10000 | Loss: 1.8264
Epoch 884/10000 | Loss: 1.8147
Epoch 886/10000 | Loss: 1.8180
Epoch 888/10000 | Loss: 1.8181
Epoch 890/10000 | Loss: 1.8162
Epoch 892/10000 | Loss: 1.8169
Epoch 894/10000 | Loss: 1.8153
Epoch 896/10000 | Loss: 1.8157
Epoch 898/10000 | Loss: 1.8156
Epoch 900/10000 | Loss: 1.8150
Epoch 902/10000 | Loss: 1.8156
Epoch 904/10000 | Loss: 1.8150
Epoch 906/10000 | Loss: 1.8153
Epoch 908/10000 | Loss: 1.8152
Epoch 910/10000 | Loss: 1.8150
Epoch 912/10000 | Loss: 1.8152
Epoch 914/10000 | Loss: 1.8150
Epoch 916/10000 | Loss: 1.8151
Epoch 918/10000 | Loss: 1.8151
Epoch 920/10000 | Loss: 1.8150
Epoch 922/10000 | Loss: 1.8150
Epoch 924/10000 | Loss: 1.8150
Epoch 926/10000 | Loss: 1.8150
Epoch 928/10000 | Loss: 1.8150
Epoch 930/10000 | Loss: 1.8150
Epoch 932/10000 | Loss: 1.8150
Epoch 934/10000 | Loss: 1.8150
Epoch 936/10000 | Loss: 1.8150
Epoch 938/10000 | Loss: 1.8150
Epoch 940/10000 | Loss: 1.8149
Epoch 942/10000 | Loss: 1.8149
Epoch 944/10000 | Loss: 1.8149
Epoch 946/10000 | Loss: 1.8149
Epoch 948/10000 | Loss: 1.8149
Epoch 950/10000 | Loss: 1.8149
Epoch 952/10000 | Loss: 1.8149
Epoch 954/10000 | Loss: 1.8149
Epoch 956/10000 | Loss: 1.8149
Epoch 958/10000 | Loss: 1.8149
Epoch 960/10000 | Loss: 1.8149
Epoch 962/10000 | Loss: 1.8149
Epoch 964/10000 | Loss: 1.8149
Epoch 966/10000 | Loss: 1.8149
Epoch 968/10000 | Loss: 1.8148
Epoch 970/10000 | Loss: 1.8148
Epoch 972/10000 | Loss: 1.8148
Epoch 974/10000 | Loss: 1.8148
Epoch 976/10000 | Loss: 1.8148
Epoch 978/10000 | Loss: 1.8148
Epoch 980/10000 | Loss: 1.8148
Epoch 982/10000 | Loss: 1.8148
Epoch 984/10000 | Loss: 1.8147
Epoch 986/10000 | Loss: 1.8147
Epoch 988/10000 | Loss: 1.8147
Epoch 990/10000 | Loss: 1.8147
Epoch 992/10000 | Loss: 1.8147
Epoch 994/10000 | Loss: 1.8146
Epoch 996/10000 | Loss: 1.8146
Epoch 998/10000 | Loss: 1.8146
Epoch 1000/10000 | Loss: 1.8145
Epoch 1002/10000 | Loss: 1.8145
Epoch 1004/10000 | Loss: 1.8145
Epoch 1006/10000 | Loss: 1.8144
Epoch 1008/10000 | Loss: 1.8144
Epoch 1010/10000 | Loss: 1.8143
Epoch 1012/10000 | Loss: 1.8143
Epoch 1014/10000 | Loss: 1.8142
Epoch 1016/10000 | Loss: 1.8141
Epoch 1018/10000 | Loss: 1.8140
Epoch 1020/10000 | Loss: 1.8139
Epoch 1022/10000 | Loss: 1.8138
Epoch 1024/10000 | Loss: 1.8142
Epoch 1026/10000 | Loss: 1.8142
Epoch 1028/10000 | Loss: 1.8141
Epoch 1030/10000 | Loss: 1.8142
Epoch 1032/10000 | Loss: 1.8142
Epoch 1034/10000 | Loss: 1.8309
Epoch 1036/10000 | Loss: 1.8259
Epoch 1038/10000 | Loss: 1.8162
Epoch 1040/10000 | Loss: 1.8200
Epoch 1042/10000 | Loss: 1.8187
Epoch 1044/10000 | Loss: 1.8152
Epoch 1046/10000 | Loss: 1.8175
Epoch 1048/10000 | Loss: 1.8158
Epoch 1050/10000 | Loss: 1.8156
Epoch 1052/10000 | Loss: 1.8164
Epoch 1054/10000 | Loss: 1.8155
Epoch 1056/10000 | Loss: 1.8153
Epoch 1058/10000 | Loss: 1.8157
Epoch 1060/10000 | Loss: 1.8152
Epoch 1062/10000 | Loss: 1.8152
Epoch 1064/10000 | Loss: 1.8154
Epoch 1066/10000 | Loss: 1.8152
Epoch 1068/10000 | Loss: 1.8151
Epoch 1070/10000 | Loss: 1.8153
Epoch 1072/10000 | Loss: 1.8151
Epoch 1074/10000 | Loss: 1.8151
Epoch 1076/10000 | Loss: 1.8152
Epoch 1078/10000 | Loss: 1.8151
Epoch 1080/10000 | Loss: 1.8151
Epoch 1082/10000 | Loss: 1.8151
Epoch 1084/10000 | Loss: 1.8151
Epoch 1086/10000 | Loss: 1.8151
Epoch 1088/10000 | Loss: 1.8151
Epoch 1090/10000 | Loss: 1.8151
Epoch 1092/10000 | Loss: 1.8151
Epoch 1094/10000 | Loss: 1.8151
Epoch 1096/10000 | Loss: 1.8151
Epoch 1098/10000 | Loss: 1.8151
Epoch 1100/10000 | Loss: 1.8151
Epoch 1102/10000 | Loss: 1.8151
Epoch 1104/10000 | Loss: 1.8151
Epoch 1106/10000 | Loss: 1.8151
Epoch 1108/10000 | Loss: 1.8151
Epoch 1110/10000 | Loss: 1.8151
Epoch 1112/10000 | Loss: 1.8151
Epoch 1114/10000 | Loss: 1.8151
Epoch 1116/10000 | Loss: 1.8151
Epoch 1118/10000 | Loss: 1.8151
Epoch 1120/10000 | Loss: 1.8151
Epoch 1122/10000 | Loss: 1.8151
Epoch 1124/10000 | Loss: 1.8151
Epoch 1126/10000 | Loss: 1.8151
Epoch 1128/10000 | Loss: 1.8151
Epoch 1130/10000 | Loss: 1.8151
Epoch 1132/10000 | Loss: 1.8151
Epoch 1134/10000 | Loss: 1.8151
Epoch 1136/10000 | Loss: 1.8151
Epoch 1138/10000 | Loss: 1.8151
Epoch 1140/10000 | Loss: 1.8151
Epoch 1142/10000 | Loss: 1.8151
Epoch 1144/10000 | Loss: 1.8151
Epoch 1146/10000 | Loss: 1.8151
Epoch 1148/10000 | Loss: 1.8151
Epoch 1150/10000 | Loss: 1.8151
Epoch 1152/10000 | Loss: 1.8151
Epoch 1154/10000 | Loss: 1.8151
Epoch 1156/10000 | Loss: 1.8151
Epoch 1158/10000 | Loss: 1.8151
Epoch 1160/10000 | Loss: 1.8151
Epoch 1162/10000 | Loss: 1.8151
Epoch 1164/10000 | Loss: 1.8151
Epoch 1166/10000 | Loss: 1.8151
Epoch 1168/10000 | Loss: 1.8151
Epoch 1170/10000 | Loss: 1.8151
Epoch 1172/10000 | Loss: 1.8151
Epoch 1174/10000 | Loss: 1.8151
Epoch 1176/10000 | Loss: 1.8151
Epoch 1178/10000 | Loss: 1.8151
Epoch 1180/10000 | Loss: 1.8151
Epoch 1182/10000 | Loss: 1.8151
Epoch 1184/10000 | Loss: 1.8151
Epoch 1186/10000 | Loss: 1.8151
Epoch 1188/10000 | Loss: 1.8151
Epoch 1190/10000 | Loss: 1.8151
Epoch 1192/10000 | Loss: 1.8151
Epoch 1194/10000 | Loss: 1.8151
Epoch 1196/10000 | Loss: 1.8151
Epoch 1198/10000 | Loss: 1.8151
Epoch 1200/10000 | Loss: 1.8151
Epoch 1202/10000 | Loss: 1.8151
Epoch 1204/10000 | Loss: 1.8151
Epoch 1206/10000 | Loss: 1.8151
Epoch 1208/10000 | Loss: 1.8151
Epoch 1210/10000 | Loss: 1.8151
Epoch 1212/10000 | Loss: 1.8151
Epoch 1214/10000 | Loss: 1.8151
Epoch 1216/10000 | Loss: 1.8151
Epoch 1218/10000 | Loss: 1.8151
Epoch 1220/10000 | Loss: 1.8151
Epoch 1222/10000 | Loss: 1.8151
Epoch 1224/10000 | Loss: 1.8151
Epoch 1226/10000 | Loss: 1.8151
Epoch 1228/10000 | Loss: 1.8151
Epoch 1230/10000 | Loss: 1.8151
Epoch 1232/10000 | Loss: 1.8151
Epoch 1234/10000 | Loss: 1.8151
Epoch 1236/10000 | Loss: 1.8151
Epoch 1238/10000 | Loss: 1.8151
Epoch 1240/10000 | Loss: 1.8151
Epoch 1242/10000 | Loss: 1.8151
Epoch 1244/10000 | Loss: 1.8151
Epoch 1246/10000 | Loss: 1.8151
Epoch 1248/10000 | Loss: 1.8151
Epoch 1250/10000 | Loss: 1.8151
Epoch 1252/10000 | Loss: 1.8151
Epoch 1254/10000 | Loss: 1.8151
Epoch 1256/10000 | Loss: 1.8151
Epoch 1258/10000 | Loss: 1.8151
Epoch 1260/10000 | Loss: 1.8151
Epoch 1262/10000 | Loss: 1.8151
Epoch 1264/10000 | Loss: 1.8151
Epoch 1266/10000 | Loss: 1.8151
Epoch 1268/10000 | Loss: 1.8151
Epoch 1270/10000 | Loss: 1.8151
Epoch 1272/10000 | Loss: 1.8151
Epoch 1274/10000 | Loss: 1.8151
Epoch 1276/10000 | Loss: 1.8151
Epoch 1278/10000 | Loss: 1.8151
Epoch 1280/10000 | Loss: 1.8151
Epoch 1282/10000 | Loss: 1.8151
Epoch 1284/10000 | Loss: 1.8151

KeyboardInterrupt: